#!/usr/bin/env python3
"""Responsibility: preserve the public cleanup API and executable script path.

Safety boundary: contains no cleanup logic; all validation and mutation gates
remain in the focused ``oci_cleanup`` implementation modules.
Cleanup sequence role: re-exports the supported API and delegates execution to
``oci_cleanup.cli.main``.

Imports from this facade remain the compatibility surface for callers and tests,
while direct invocation forwards arguments and exit status to the package CLI.
"""

from __future__ import annotations

import sys

from oci_cleanup import (
    OWNER_KEY,
    OWNER_VALUE,
    AUTO_COMPARTMENT_NAME,
    AUTO_COMPARTMENT_DESCRIPTION,
    USER_NAME,
    GROUP_NAME,
    USER_POLICY_NAME,
    DYNAMIC_POLICY_NAME,
    CONNECTOR_GROUP_NAME,
    FUNCTION_GROUP_NAME,
    CONNECTOR_GROUP_DESCRIPTION,
    FUNCTION_GROUP_DESCRIPTION,
    TAG_NAMESPACE_NAME,
    TAG_NAME,
    REGIONAL_STACK_PREFIX,
    FUNCTION_APP_NAME,
    FUNCTION_NAMES,
    BACKFILL_BUCKET_NAMES,
    VCN_NAME,
    SUBNET_NAME,
    NAT_GATEWAY_NAME,
    SERVICE_GATEWAY_NAME,
    VAULT_NAME,
    KEY_NAME,
    SECRET_NAME,
    SECRET_DELETION_DELAY,
    KMS_DELETION_DELAY,
    SUBNET_VNIC_RETRY_SECONDS,
    SUBNET_VNIC_RETRY_INTERVAL_SECONDS,
    LOGGER,
    CleanupError,
    CommandError,
    utc_now,
    resource_id,
    resource_name,
    resource_compartment,
    lifecycle_state,
    is_deleted_or_deleting,
    data_items,
    freeform_tags,
    defined_marker,
    is_owned,
    exact_owned,
    Manifest,
    OciCli,
    CleanupContext,
    ExtraResourceCandidate,
    QuickstartCleanup,
    parse_args,
    main,
)

__all__ = [
    "OWNER_KEY",
    "OWNER_VALUE",
    "AUTO_COMPARTMENT_NAME",
    "AUTO_COMPARTMENT_DESCRIPTION",
    "USER_NAME",
    "GROUP_NAME",
    "USER_POLICY_NAME",
    "DYNAMIC_POLICY_NAME",
    "CONNECTOR_GROUP_NAME",
    "FUNCTION_GROUP_NAME",
    "CONNECTOR_GROUP_DESCRIPTION",
    "FUNCTION_GROUP_DESCRIPTION",
    "TAG_NAMESPACE_NAME",
    "TAG_NAME",
    "REGIONAL_STACK_PREFIX",
    "FUNCTION_APP_NAME",
    "FUNCTION_NAMES",
    "BACKFILL_BUCKET_NAMES",
    "VCN_NAME",
    "SUBNET_NAME",
    "NAT_GATEWAY_NAME",
    "SERVICE_GATEWAY_NAME",
    "VAULT_NAME",
    "KEY_NAME",
    "SECRET_NAME",
    "SECRET_DELETION_DELAY",
    "KMS_DELETION_DELAY",
    "SUBNET_VNIC_RETRY_SECONDS",
    "SUBNET_VNIC_RETRY_INTERVAL_SECONDS",
    "LOGGER",
    "CleanupError",
    "CommandError",
    "utc_now",
    "resource_id",
    "resource_name",
    "resource_compartment",
    "lifecycle_state",
    "is_deleted_or_deleting",
    "data_items",
    "freeform_tags",
    "defined_marker",
    "is_owned",
    "exact_owned",
    "Manifest",
    "OciCli",
    "CleanupContext",
    "ExtraResourceCandidate",
    "QuickstartCleanup",
    "parse_args",
    "main",
]

if __name__ == "__main__":
    sys.exit(main())
