# Autogenerated tf file through the generator script. DO NOT EDIT
# Run generator.sh to regenerate after adding regions

provider "oci" {
  tenancy_ocid = var.tenancy_ocid
  region       = "af-johannesburg-1"
  alias        = "af-johannesburg-1"
}

provider "oci" {
  tenancy_ocid = var.tenancy_ocid
  region       = "ap-chuncheon-1"
  alias        = "ap-chuncheon-1"
}

provider "oci" {
  tenancy_ocid = var.tenancy_ocid
  region       = "ap-hyderabad-1"
  alias        = "ap-hyderabad-1"
}

provider "oci" {
  tenancy_ocid = var.tenancy_ocid
  region       = "ap-melbourne-1"
  alias        = "ap-melbourne-1"
}

provider "oci" {
  tenancy_ocid = var.tenancy_ocid
  region       = "ap-mumbai-1"
  alias        = "ap-mumbai-1"
}

provider "oci" {
  tenancy_ocid = var.tenancy_ocid
  region       = "ap-osaka-1"
  alias        = "ap-osaka-1"
}

provider "oci" {
  tenancy_ocid = var.tenancy_ocid
  region       = "ap-seoul-1"
  alias        = "ap-seoul-1"
}

provider "oci" {
  tenancy_ocid = var.tenancy_ocid
  region       = "ap-singapore-1"
  alias        = "ap-singapore-1"
}

provider "oci" {
  tenancy_ocid = var.tenancy_ocid
  region       = "ap-singapore-2"
  alias        = "ap-singapore-2"
}

provider "oci" {
  tenancy_ocid = var.tenancy_ocid
  region       = "ap-sydney-1"
  alias        = "ap-sydney-1"
}

provider "oci" {
  tenancy_ocid = var.tenancy_ocid
  region       = "ap-tokyo-1"
  alias        = "ap-tokyo-1"
}

provider "oci" {
  tenancy_ocid = var.tenancy_ocid
  region       = "ca-montreal-1"
  alias        = "ca-montreal-1"
}

provider "oci" {
  tenancy_ocid = var.tenancy_ocid
  region       = "ca-toronto-1"
  alias        = "ca-toronto-1"
}

provider "oci" {
  tenancy_ocid = var.tenancy_ocid
  region       = "eu-amsterdam-1"
  alias        = "eu-amsterdam-1"
}

provider "oci" {
  tenancy_ocid = var.tenancy_ocid
  region       = "eu-frankfurt-1"
  alias        = "eu-frankfurt-1"
}

provider "oci" {
  tenancy_ocid = var.tenancy_ocid
  region       = "eu-madrid-1"
  alias        = "eu-madrid-1"
}

provider "oci" {
  tenancy_ocid = var.tenancy_ocid
  region       = "eu-marseille-1"
  alias        = "eu-marseille-1"
}

provider "oci" {
  tenancy_ocid = var.tenancy_ocid
  region       = "eu-milan-1"
  alias        = "eu-milan-1"
}

provider "oci" {
  tenancy_ocid = var.tenancy_ocid
  region       = "eu-paris-1"
  alias        = "eu-paris-1"
}

provider "oci" {
  tenancy_ocid = var.tenancy_ocid
  region       = "eu-stockholm-1"
  alias        = "eu-stockholm-1"
}

provider "oci" {
  tenancy_ocid = var.tenancy_ocid
  region       = "eu-zurich-1"
  alias        = "eu-zurich-1"
}

provider "oci" {
  tenancy_ocid = var.tenancy_ocid
  region       = "il-jerusalem-1"
  alias        = "il-jerusalem-1"
}

provider "oci" {
  tenancy_ocid = var.tenancy_ocid
  region       = "me-abudhabi-1"
  alias        = "me-abudhabi-1"
}

provider "oci" {
  tenancy_ocid = var.tenancy_ocid
  region       = "me-dubai-1"
  alias        = "me-dubai-1"
}

provider "oci" {
  tenancy_ocid = var.tenancy_ocid
  region       = "me-jeddah-1"
  alias        = "me-jeddah-1"
}

provider "oci" {
  tenancy_ocid = var.tenancy_ocid
  region       = "me-riyadh-1"
  alias        = "me-riyadh-1"
}

provider "oci" {
  tenancy_ocid = var.tenancy_ocid
  region       = "mx-monterrey-1"
  alias        = "mx-monterrey-1"
}

provider "oci" {
  tenancy_ocid = var.tenancy_ocid
  region       = "mx-queretaro-1"
  alias        = "mx-queretaro-1"
}

provider "oci" {
  tenancy_ocid = var.tenancy_ocid
  region       = "sa-bogota-1"
  alias        = "sa-bogota-1"
}

provider "oci" {
  tenancy_ocid = var.tenancy_ocid
  region       = "sa-santiago-1"
  alias        = "sa-santiago-1"
}

provider "oci" {
  tenancy_ocid = var.tenancy_ocid
  region       = "sa-saopaulo-1"
  alias        = "sa-saopaulo-1"
}

provider "oci" {
  tenancy_ocid = var.tenancy_ocid
  region       = "sa-valparaiso-1"
  alias        = "sa-valparaiso-1"
}

provider "oci" {
  tenancy_ocid = var.tenancy_ocid
  region       = "sa-vinhedo-1"
  alias        = "sa-vinhedo-1"
}

provider "oci" {
  tenancy_ocid = var.tenancy_ocid
  region       = "uk-cardiff-1"
  alias        = "uk-cardiff-1"
}

provider "oci" {
  tenancy_ocid = var.tenancy_ocid
  region       = "uk-london-1"
  alias        = "uk-london-1"
}

provider "oci" {
  tenancy_ocid = var.tenancy_ocid
  region       = "us-ashburn-1"
  alias        = "us-ashburn-1"
}

provider "oci" {
  tenancy_ocid = var.tenancy_ocid
  region       = "us-chicago-1"
  alias        = "us-chicago-1"
}

provider "oci" {
  tenancy_ocid = var.tenancy_ocid
  region       = "us-phoenix-1"
  alias        = "us-phoenix-1"
}

provider "oci" {
  tenancy_ocid = var.tenancy_ocid
  region       = "us-sanjose-1"
  alias        = "us-sanjose-1"
}

# End of autogenerated code
