# Autogenerated tf file through the generator script. DO NOT EDIT
# Run generator.sh to regenerate after adding regions

module "networking_af-johannesburg-1" {
  source = "./modules/networking"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "af-johannesburg-1") ? 1 : 0
  providers = {
    oci = oci.af-johannesburg-1
  }
  compartment_id = module.compartment.id
  tags           = local.tags
}

module "functions_af-johannesburg-1" {
  source = "./modules/functions"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "af-johannesburg-1") ? 1 : 0
  providers = {
    oci = oci.af-johannesburg-1
  }
  tenancy_id        = var.tenancy_ocid
  compartment_id    = module.compartment.id
  subnet_id         = module.networking_af-johannesburg-1[0].subnet_id
  tags              = local.tags
  datadog_site      = var.datadog_site
  home_region       = local.home_region_name
  api_key_secret_id = length(module.kms) > 0 ? module.kms[0].api_key_secret_id : ""
  region_key        = local.subscribed_regions_map["af-johannesburg-1"].region_key
}

module "networking_ap-chuncheon-1" {
  source = "./modules/networking"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "ap-chuncheon-1") ? 1 : 0
  providers = {
    oci = oci.ap-chuncheon-1
  }
  compartment_id = module.compartment.id
  tags           = local.tags
}

module "functions_ap-chuncheon-1" {
  source = "./modules/functions"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "ap-chuncheon-1") ? 1 : 0
  providers = {
    oci = oci.ap-chuncheon-1
  }
  tenancy_id        = var.tenancy_ocid
  compartment_id    = module.compartment.id
  subnet_id         = module.networking_ap-chuncheon-1[0].subnet_id
  tags              = local.tags
  datadog_site      = var.datadog_site
  home_region       = local.home_region_name
  api_key_secret_id = length(module.kms) > 0 ? module.kms[0].api_key_secret_id : ""
  region_key        = local.subscribed_regions_map["ap-chuncheon-1"].region_key
}

module "networking_ap-hyderabad-1" {
  source = "./modules/networking"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "ap-hyderabad-1") ? 1 : 0
  providers = {
    oci = oci.ap-hyderabad-1
  }
  compartment_id = module.compartment.id
  tags           = local.tags
}

module "functions_ap-hyderabad-1" {
  source = "./modules/functions"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "ap-hyderabad-1") ? 1 : 0
  providers = {
    oci = oci.ap-hyderabad-1
  }
  tenancy_id        = var.tenancy_ocid
  compartment_id    = module.compartment.id
  subnet_id         = module.networking_ap-hyderabad-1[0].subnet_id
  tags              = local.tags
  datadog_site      = var.datadog_site
  home_region       = local.home_region_name
  api_key_secret_id = length(module.kms) > 0 ? module.kms[0].api_key_secret_id : ""
  region_key        = local.subscribed_regions_map["ap-hyderabad-1"].region_key
}

module "networking_ap-melbourne-1" {
  source = "./modules/networking"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "ap-melbourne-1") ? 1 : 0
  providers = {
    oci = oci.ap-melbourne-1
  }
  compartment_id = module.compartment.id
  tags           = local.tags
}

module "functions_ap-melbourne-1" {
  source = "./modules/functions"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "ap-melbourne-1") ? 1 : 0
  providers = {
    oci = oci.ap-melbourne-1
  }
  tenancy_id        = var.tenancy_ocid
  compartment_id    = module.compartment.id
  subnet_id         = module.networking_ap-melbourne-1[0].subnet_id
  tags              = local.tags
  datadog_site      = var.datadog_site
  home_region       = local.home_region_name
  api_key_secret_id = length(module.kms) > 0 ? module.kms[0].api_key_secret_id : ""
  region_key        = local.subscribed_regions_map["ap-melbourne-1"].region_key
}

module "networking_ap-mumbai-1" {
  source = "./modules/networking"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "ap-mumbai-1") ? 1 : 0
  providers = {
    oci = oci.ap-mumbai-1
  }
  compartment_id = module.compartment.id
  tags           = local.tags
}

module "functions_ap-mumbai-1" {
  source = "./modules/functions"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "ap-mumbai-1") ? 1 : 0
  providers = {
    oci = oci.ap-mumbai-1
  }
  tenancy_id        = var.tenancy_ocid
  compartment_id    = module.compartment.id
  subnet_id         = module.networking_ap-mumbai-1[0].subnet_id
  tags              = local.tags
  datadog_site      = var.datadog_site
  home_region       = local.home_region_name
  api_key_secret_id = length(module.kms) > 0 ? module.kms[0].api_key_secret_id : ""
  region_key        = local.subscribed_regions_map["ap-mumbai-1"].region_key
}

module "networking_ap-osaka-1" {
  source = "./modules/networking"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "ap-osaka-1") ? 1 : 0
  providers = {
    oci = oci.ap-osaka-1
  }
  compartment_id = module.compartment.id
  tags           = local.tags
}

module "functions_ap-osaka-1" {
  source = "./modules/functions"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "ap-osaka-1") ? 1 : 0
  providers = {
    oci = oci.ap-osaka-1
  }
  tenancy_id        = var.tenancy_ocid
  compartment_id    = module.compartment.id
  subnet_id         = module.networking_ap-osaka-1[0].subnet_id
  tags              = local.tags
  datadog_site      = var.datadog_site
  home_region       = local.home_region_name
  api_key_secret_id = length(module.kms) > 0 ? module.kms[0].api_key_secret_id : ""
  region_key        = local.subscribed_regions_map["ap-osaka-1"].region_key
}

module "networking_ap-seoul-1" {
  source = "./modules/networking"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "ap-seoul-1") ? 1 : 0
  providers = {
    oci = oci.ap-seoul-1
  }
  compartment_id = module.compartment.id
  tags           = local.tags
}

module "functions_ap-seoul-1" {
  source = "./modules/functions"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "ap-seoul-1") ? 1 : 0
  providers = {
    oci = oci.ap-seoul-1
  }
  tenancy_id        = var.tenancy_ocid
  compartment_id    = module.compartment.id
  subnet_id         = module.networking_ap-seoul-1[0].subnet_id
  tags              = local.tags
  datadog_site      = var.datadog_site
  home_region       = local.home_region_name
  api_key_secret_id = length(module.kms) > 0 ? module.kms[0].api_key_secret_id : ""
  region_key        = local.subscribed_regions_map["ap-seoul-1"].region_key
}

module "networking_ap-singapore-1" {
  source = "./modules/networking"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "ap-singapore-1") ? 1 : 0
  providers = {
    oci = oci.ap-singapore-1
  }
  compartment_id = module.compartment.id
  tags           = local.tags
}

module "functions_ap-singapore-1" {
  source = "./modules/functions"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "ap-singapore-1") ? 1 : 0
  providers = {
    oci = oci.ap-singapore-1
  }
  tenancy_id        = var.tenancy_ocid
  compartment_id    = module.compartment.id
  subnet_id         = module.networking_ap-singapore-1[0].subnet_id
  tags              = local.tags
  datadog_site      = var.datadog_site
  home_region       = local.home_region_name
  api_key_secret_id = length(module.kms) > 0 ? module.kms[0].api_key_secret_id : ""
  region_key        = local.subscribed_regions_map["ap-singapore-1"].region_key
}

module "networking_ap-singapore-2" {
  source = "./modules/networking"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "ap-singapore-2") ? 1 : 0
  providers = {
    oci = oci.ap-singapore-2
  }
  compartment_id = module.compartment.id
  tags           = local.tags
}

module "functions_ap-singapore-2" {
  source = "./modules/functions"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "ap-singapore-2") ? 1 : 0
  providers = {
    oci = oci.ap-singapore-2
  }
  tenancy_id        = var.tenancy_ocid
  compartment_id    = module.compartment.id
  subnet_id         = module.networking_ap-singapore-2[0].subnet_id
  tags              = local.tags
  datadog_site      = var.datadog_site
  home_region       = local.home_region_name
  api_key_secret_id = length(module.kms) > 0 ? module.kms[0].api_key_secret_id : ""
  region_key        = local.subscribed_regions_map["ap-singapore-2"].region_key
}

module "networking_ap-sydney-1" {
  source = "./modules/networking"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "ap-sydney-1") ? 1 : 0
  providers = {
    oci = oci.ap-sydney-1
  }
  compartment_id = module.compartment.id
  tags           = local.tags
}

module "functions_ap-sydney-1" {
  source = "./modules/functions"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "ap-sydney-1") ? 1 : 0
  providers = {
    oci = oci.ap-sydney-1
  }
  tenancy_id        = var.tenancy_ocid
  compartment_id    = module.compartment.id
  subnet_id         = module.networking_ap-sydney-1[0].subnet_id
  tags              = local.tags
  datadog_site      = var.datadog_site
  home_region       = local.home_region_name
  api_key_secret_id = length(module.kms) > 0 ? module.kms[0].api_key_secret_id : ""
  region_key        = local.subscribed_regions_map["ap-sydney-1"].region_key
}

module "networking_ap-tokyo-1" {
  source = "./modules/networking"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "ap-tokyo-1") ? 1 : 0
  providers = {
    oci = oci.ap-tokyo-1
  }
  compartment_id = module.compartment.id
  tags           = local.tags
}

module "functions_ap-tokyo-1" {
  source = "./modules/functions"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "ap-tokyo-1") ? 1 : 0
  providers = {
    oci = oci.ap-tokyo-1
  }
  tenancy_id        = var.tenancy_ocid
  compartment_id    = module.compartment.id
  subnet_id         = module.networking_ap-tokyo-1[0].subnet_id
  tags              = local.tags
  datadog_site      = var.datadog_site
  home_region       = local.home_region_name
  api_key_secret_id = length(module.kms) > 0 ? module.kms[0].api_key_secret_id : ""
  region_key        = local.subscribed_regions_map["ap-tokyo-1"].region_key
}

module "networking_ca-montreal-1" {
  source = "./modules/networking"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "ca-montreal-1") ? 1 : 0
  providers = {
    oci = oci.ca-montreal-1
  }
  compartment_id = module.compartment.id
  tags           = local.tags
}

module "functions_ca-montreal-1" {
  source = "./modules/functions"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "ca-montreal-1") ? 1 : 0
  providers = {
    oci = oci.ca-montreal-1
  }
  tenancy_id        = var.tenancy_ocid
  compartment_id    = module.compartment.id
  subnet_id         = module.networking_ca-montreal-1[0].subnet_id
  tags              = local.tags
  datadog_site      = var.datadog_site
  home_region       = local.home_region_name
  api_key_secret_id = length(module.kms) > 0 ? module.kms[0].api_key_secret_id : ""
  region_key        = local.subscribed_regions_map["ca-montreal-1"].region_key
}

module "networking_ca-toronto-1" {
  source = "./modules/networking"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "ca-toronto-1") ? 1 : 0
  providers = {
    oci = oci.ca-toronto-1
  }
  compartment_id = module.compartment.id
  tags           = local.tags
}

module "functions_ca-toronto-1" {
  source = "./modules/functions"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "ca-toronto-1") ? 1 : 0
  providers = {
    oci = oci.ca-toronto-1
  }
  tenancy_id        = var.tenancy_ocid
  compartment_id    = module.compartment.id
  subnet_id         = module.networking_ca-toronto-1[0].subnet_id
  tags              = local.tags
  datadog_site      = var.datadog_site
  home_region       = local.home_region_name
  api_key_secret_id = length(module.kms) > 0 ? module.kms[0].api_key_secret_id : ""
  region_key        = local.subscribed_regions_map["ca-toronto-1"].region_key
}

module "networking_eu-amsterdam-1" {
  source = "./modules/networking"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "eu-amsterdam-1") ? 1 : 0
  providers = {
    oci = oci.eu-amsterdam-1
  }
  compartment_id = module.compartment.id
  tags           = local.tags
}

module "functions_eu-amsterdam-1" {
  source = "./modules/functions"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "eu-amsterdam-1") ? 1 : 0
  providers = {
    oci = oci.eu-amsterdam-1
  }
  tenancy_id        = var.tenancy_ocid
  compartment_id    = module.compartment.id
  subnet_id         = module.networking_eu-amsterdam-1[0].subnet_id
  tags              = local.tags
  datadog_site      = var.datadog_site
  home_region       = local.home_region_name
  api_key_secret_id = length(module.kms) > 0 ? module.kms[0].api_key_secret_id : ""
  region_key        = local.subscribed_regions_map["eu-amsterdam-1"].region_key
}

module "networking_eu-frankfurt-1" {
  source = "./modules/networking"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "eu-frankfurt-1") ? 1 : 0
  providers = {
    oci = oci.eu-frankfurt-1
  }
  compartment_id = module.compartment.id
  tags           = local.tags
}

module "functions_eu-frankfurt-1" {
  source = "./modules/functions"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "eu-frankfurt-1") ? 1 : 0
  providers = {
    oci = oci.eu-frankfurt-1
  }
  tenancy_id        = var.tenancy_ocid
  compartment_id    = module.compartment.id
  subnet_id         = module.networking_eu-frankfurt-1[0].subnet_id
  tags              = local.tags
  datadog_site      = var.datadog_site
  home_region       = local.home_region_name
  api_key_secret_id = length(module.kms) > 0 ? module.kms[0].api_key_secret_id : ""
  region_key        = local.subscribed_regions_map["eu-frankfurt-1"].region_key
}

module "networking_eu-madrid-1" {
  source = "./modules/networking"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "eu-madrid-1") ? 1 : 0
  providers = {
    oci = oci.eu-madrid-1
  }
  compartment_id = module.compartment.id
  tags           = local.tags
}

module "functions_eu-madrid-1" {
  source = "./modules/functions"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "eu-madrid-1") ? 1 : 0
  providers = {
    oci = oci.eu-madrid-1
  }
  tenancy_id        = var.tenancy_ocid
  compartment_id    = module.compartment.id
  subnet_id         = module.networking_eu-madrid-1[0].subnet_id
  tags              = local.tags
  datadog_site      = var.datadog_site
  home_region       = local.home_region_name
  api_key_secret_id = length(module.kms) > 0 ? module.kms[0].api_key_secret_id : ""
  region_key        = local.subscribed_regions_map["eu-madrid-1"].region_key
}

module "networking_eu-marseille-1" {
  source = "./modules/networking"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "eu-marseille-1") ? 1 : 0
  providers = {
    oci = oci.eu-marseille-1
  }
  compartment_id = module.compartment.id
  tags           = local.tags
}

module "functions_eu-marseille-1" {
  source = "./modules/functions"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "eu-marseille-1") ? 1 : 0
  providers = {
    oci = oci.eu-marseille-1
  }
  tenancy_id        = var.tenancy_ocid
  compartment_id    = module.compartment.id
  subnet_id         = module.networking_eu-marseille-1[0].subnet_id
  tags              = local.tags
  datadog_site      = var.datadog_site
  home_region       = local.home_region_name
  api_key_secret_id = length(module.kms) > 0 ? module.kms[0].api_key_secret_id : ""
  region_key        = local.subscribed_regions_map["eu-marseille-1"].region_key
}

module "networking_eu-milan-1" {
  source = "./modules/networking"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "eu-milan-1") ? 1 : 0
  providers = {
    oci = oci.eu-milan-1
  }
  compartment_id = module.compartment.id
  tags           = local.tags
}

module "functions_eu-milan-1" {
  source = "./modules/functions"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "eu-milan-1") ? 1 : 0
  providers = {
    oci = oci.eu-milan-1
  }
  tenancy_id        = var.tenancy_ocid
  compartment_id    = module.compartment.id
  subnet_id         = module.networking_eu-milan-1[0].subnet_id
  tags              = local.tags
  datadog_site      = var.datadog_site
  home_region       = local.home_region_name
  api_key_secret_id = length(module.kms) > 0 ? module.kms[0].api_key_secret_id : ""
  region_key        = local.subscribed_regions_map["eu-milan-1"].region_key
}

module "networking_eu-paris-1" {
  source = "./modules/networking"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "eu-paris-1") ? 1 : 0
  providers = {
    oci = oci.eu-paris-1
  }
  compartment_id = module.compartment.id
  tags           = local.tags
}

module "functions_eu-paris-1" {
  source = "./modules/functions"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "eu-paris-1") ? 1 : 0
  providers = {
    oci = oci.eu-paris-1
  }
  tenancy_id        = var.tenancy_ocid
  compartment_id    = module.compartment.id
  subnet_id         = module.networking_eu-paris-1[0].subnet_id
  tags              = local.tags
  datadog_site      = var.datadog_site
  home_region       = local.home_region_name
  api_key_secret_id = length(module.kms) > 0 ? module.kms[0].api_key_secret_id : ""
  region_key        = local.subscribed_regions_map["eu-paris-1"].region_key
}

module "networking_eu-stockholm-1" {
  source = "./modules/networking"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "eu-stockholm-1") ? 1 : 0
  providers = {
    oci = oci.eu-stockholm-1
  }
  compartment_id = module.compartment.id
  tags           = local.tags
}

module "functions_eu-stockholm-1" {
  source = "./modules/functions"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "eu-stockholm-1") ? 1 : 0
  providers = {
    oci = oci.eu-stockholm-1
  }
  tenancy_id        = var.tenancy_ocid
  compartment_id    = module.compartment.id
  subnet_id         = module.networking_eu-stockholm-1[0].subnet_id
  tags              = local.tags
  datadog_site      = var.datadog_site
  home_region       = local.home_region_name
  api_key_secret_id = length(module.kms) > 0 ? module.kms[0].api_key_secret_id : ""
  region_key        = local.subscribed_regions_map["eu-stockholm-1"].region_key
}

module "networking_eu-zurich-1" {
  source = "./modules/networking"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "eu-zurich-1") ? 1 : 0
  providers = {
    oci = oci.eu-zurich-1
  }
  compartment_id = module.compartment.id
  tags           = local.tags
}

module "functions_eu-zurich-1" {
  source = "./modules/functions"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "eu-zurich-1") ? 1 : 0
  providers = {
    oci = oci.eu-zurich-1
  }
  tenancy_id        = var.tenancy_ocid
  compartment_id    = module.compartment.id
  subnet_id         = module.networking_eu-zurich-1[0].subnet_id
  tags              = local.tags
  datadog_site      = var.datadog_site
  home_region       = local.home_region_name
  api_key_secret_id = length(module.kms) > 0 ? module.kms[0].api_key_secret_id : ""
  region_key        = local.subscribed_regions_map["eu-zurich-1"].region_key
}

module "networking_il-jerusalem-1" {
  source = "./modules/networking"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "il-jerusalem-1") ? 1 : 0
  providers = {
    oci = oci.il-jerusalem-1
  }
  compartment_id = module.compartment.id
  tags           = local.tags
}

module "functions_il-jerusalem-1" {
  source = "./modules/functions"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "il-jerusalem-1") ? 1 : 0
  providers = {
    oci = oci.il-jerusalem-1
  }
  tenancy_id        = var.tenancy_ocid
  compartment_id    = module.compartment.id
  subnet_id         = module.networking_il-jerusalem-1[0].subnet_id
  tags              = local.tags
  datadog_site      = var.datadog_site
  home_region       = local.home_region_name
  api_key_secret_id = length(module.kms) > 0 ? module.kms[0].api_key_secret_id : ""
  region_key        = local.subscribed_regions_map["il-jerusalem-1"].region_key
}

module "networking_me-abudhabi-1" {
  source = "./modules/networking"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "me-abudhabi-1") ? 1 : 0
  providers = {
    oci = oci.me-abudhabi-1
  }
  compartment_id = module.compartment.id
  tags           = local.tags
}

module "functions_me-abudhabi-1" {
  source = "./modules/functions"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "me-abudhabi-1") ? 1 : 0
  providers = {
    oci = oci.me-abudhabi-1
  }
  tenancy_id        = var.tenancy_ocid
  compartment_id    = module.compartment.id
  subnet_id         = module.networking_me-abudhabi-1[0].subnet_id
  tags              = local.tags
  datadog_site      = var.datadog_site
  home_region       = local.home_region_name
  api_key_secret_id = length(module.kms) > 0 ? module.kms[0].api_key_secret_id : ""
  region_key        = local.subscribed_regions_map["me-abudhabi-1"].region_key
}

module "networking_me-dubai-1" {
  source = "./modules/networking"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "me-dubai-1") ? 1 : 0
  providers = {
    oci = oci.me-dubai-1
  }
  compartment_id = module.compartment.id
  tags           = local.tags
}

module "functions_me-dubai-1" {
  source = "./modules/functions"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "me-dubai-1") ? 1 : 0
  providers = {
    oci = oci.me-dubai-1
  }
  tenancy_id        = var.tenancy_ocid
  compartment_id    = module.compartment.id
  subnet_id         = module.networking_me-dubai-1[0].subnet_id
  tags              = local.tags
  datadog_site      = var.datadog_site
  home_region       = local.home_region_name
  api_key_secret_id = length(module.kms) > 0 ? module.kms[0].api_key_secret_id : ""
  region_key        = local.subscribed_regions_map["me-dubai-1"].region_key
}

module "networking_me-jeddah-1" {
  source = "./modules/networking"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "me-jeddah-1") ? 1 : 0
  providers = {
    oci = oci.me-jeddah-1
  }
  compartment_id = module.compartment.id
  tags           = local.tags
}

module "functions_me-jeddah-1" {
  source = "./modules/functions"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "me-jeddah-1") ? 1 : 0
  providers = {
    oci = oci.me-jeddah-1
  }
  tenancy_id        = var.tenancy_ocid
  compartment_id    = module.compartment.id
  subnet_id         = module.networking_me-jeddah-1[0].subnet_id
  tags              = local.tags
  datadog_site      = var.datadog_site
  home_region       = local.home_region_name
  api_key_secret_id = length(module.kms) > 0 ? module.kms[0].api_key_secret_id : ""
  region_key        = local.subscribed_regions_map["me-jeddah-1"].region_key
}

module "networking_me-riyadh-1" {
  source = "./modules/networking"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "me-riyadh-1") ? 1 : 0
  providers = {
    oci = oci.me-riyadh-1
  }
  compartment_id = module.compartment.id
  tags           = local.tags
}

module "functions_me-riyadh-1" {
  source = "./modules/functions"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "me-riyadh-1") ? 1 : 0
  providers = {
    oci = oci.me-riyadh-1
  }
  tenancy_id        = var.tenancy_ocid
  compartment_id    = module.compartment.id
  subnet_id         = module.networking_me-riyadh-1[0].subnet_id
  tags              = local.tags
  datadog_site      = var.datadog_site
  home_region       = local.home_region_name
  api_key_secret_id = length(module.kms) > 0 ? module.kms[0].api_key_secret_id : ""
  region_key        = local.subscribed_regions_map["me-riyadh-1"].region_key
}

module "networking_mx-monterrey-1" {
  source = "./modules/networking"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "mx-monterrey-1") ? 1 : 0
  providers = {
    oci = oci.mx-monterrey-1
  }
  compartment_id = module.compartment.id
  tags           = local.tags
}

module "functions_mx-monterrey-1" {
  source = "./modules/functions"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "mx-monterrey-1") ? 1 : 0
  providers = {
    oci = oci.mx-monterrey-1
  }
  tenancy_id        = var.tenancy_ocid
  compartment_id    = module.compartment.id
  subnet_id         = module.networking_mx-monterrey-1[0].subnet_id
  tags              = local.tags
  datadog_site      = var.datadog_site
  home_region       = local.home_region_name
  api_key_secret_id = length(module.kms) > 0 ? module.kms[0].api_key_secret_id : ""
  region_key        = local.subscribed_regions_map["mx-monterrey-1"].region_key
}

module "networking_mx-queretaro-1" {
  source = "./modules/networking"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "mx-queretaro-1") ? 1 : 0
  providers = {
    oci = oci.mx-queretaro-1
  }
  compartment_id = module.compartment.id
  tags           = local.tags
}

module "functions_mx-queretaro-1" {
  source = "./modules/functions"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "mx-queretaro-1") ? 1 : 0
  providers = {
    oci = oci.mx-queretaro-1
  }
  tenancy_id        = var.tenancy_ocid
  compartment_id    = module.compartment.id
  subnet_id         = module.networking_mx-queretaro-1[0].subnet_id
  tags              = local.tags
  datadog_site      = var.datadog_site
  home_region       = local.home_region_name
  api_key_secret_id = length(module.kms) > 0 ? module.kms[0].api_key_secret_id : ""
  region_key        = local.subscribed_regions_map["mx-queretaro-1"].region_key
}

module "networking_sa-bogota-1" {
  source = "./modules/networking"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "sa-bogota-1") ? 1 : 0
  providers = {
    oci = oci.sa-bogota-1
  }
  compartment_id = module.compartment.id
  tags           = local.tags
}

module "functions_sa-bogota-1" {
  source = "./modules/functions"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "sa-bogota-1") ? 1 : 0
  providers = {
    oci = oci.sa-bogota-1
  }
  tenancy_id        = var.tenancy_ocid
  compartment_id    = module.compartment.id
  subnet_id         = module.networking_sa-bogota-1[0].subnet_id
  tags              = local.tags
  datadog_site      = var.datadog_site
  home_region       = local.home_region_name
  api_key_secret_id = length(module.kms) > 0 ? module.kms[0].api_key_secret_id : ""
  region_key        = local.subscribed_regions_map["sa-bogota-1"].region_key
}

module "networking_sa-santiago-1" {
  source = "./modules/networking"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "sa-santiago-1") ? 1 : 0
  providers = {
    oci = oci.sa-santiago-1
  }
  compartment_id = module.compartment.id
  tags           = local.tags
}

module "functions_sa-santiago-1" {
  source = "./modules/functions"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "sa-santiago-1") ? 1 : 0
  providers = {
    oci = oci.sa-santiago-1
  }
  tenancy_id        = var.tenancy_ocid
  compartment_id    = module.compartment.id
  subnet_id         = module.networking_sa-santiago-1[0].subnet_id
  tags              = local.tags
  datadog_site      = var.datadog_site
  home_region       = local.home_region_name
  api_key_secret_id = length(module.kms) > 0 ? module.kms[0].api_key_secret_id : ""
  region_key        = local.subscribed_regions_map["sa-santiago-1"].region_key
}

module "networking_sa-saopaulo-1" {
  source = "./modules/networking"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "sa-saopaulo-1") ? 1 : 0
  providers = {
    oci = oci.sa-saopaulo-1
  }
  compartment_id = module.compartment.id
  tags           = local.tags
}

module "functions_sa-saopaulo-1" {
  source = "./modules/functions"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "sa-saopaulo-1") ? 1 : 0
  providers = {
    oci = oci.sa-saopaulo-1
  }
  tenancy_id        = var.tenancy_ocid
  compartment_id    = module.compartment.id
  subnet_id         = module.networking_sa-saopaulo-1[0].subnet_id
  tags              = local.tags
  datadog_site      = var.datadog_site
  home_region       = local.home_region_name
  api_key_secret_id = length(module.kms) > 0 ? module.kms[0].api_key_secret_id : ""
  region_key        = local.subscribed_regions_map["sa-saopaulo-1"].region_key
}

module "networking_sa-valparaiso-1" {
  source = "./modules/networking"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "sa-valparaiso-1") ? 1 : 0
  providers = {
    oci = oci.sa-valparaiso-1
  }
  compartment_id = module.compartment.id
  tags           = local.tags
}

module "functions_sa-valparaiso-1" {
  source = "./modules/functions"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "sa-valparaiso-1") ? 1 : 0
  providers = {
    oci = oci.sa-valparaiso-1
  }
  tenancy_id        = var.tenancy_ocid
  compartment_id    = module.compartment.id
  subnet_id         = module.networking_sa-valparaiso-1[0].subnet_id
  tags              = local.tags
  datadog_site      = var.datadog_site
  home_region       = local.home_region_name
  api_key_secret_id = length(module.kms) > 0 ? module.kms[0].api_key_secret_id : ""
  region_key        = local.subscribed_regions_map["sa-valparaiso-1"].region_key
}

module "networking_sa-vinhedo-1" {
  source = "./modules/networking"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "sa-vinhedo-1") ? 1 : 0
  providers = {
    oci = oci.sa-vinhedo-1
  }
  compartment_id = module.compartment.id
  tags           = local.tags
}

module "functions_sa-vinhedo-1" {
  source = "./modules/functions"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "sa-vinhedo-1") ? 1 : 0
  providers = {
    oci = oci.sa-vinhedo-1
  }
  tenancy_id        = var.tenancy_ocid
  compartment_id    = module.compartment.id
  subnet_id         = module.networking_sa-vinhedo-1[0].subnet_id
  tags              = local.tags
  datadog_site      = var.datadog_site
  home_region       = local.home_region_name
  api_key_secret_id = length(module.kms) > 0 ? module.kms[0].api_key_secret_id : ""
  region_key        = local.subscribed_regions_map["sa-vinhedo-1"].region_key
}

module "networking_uk-cardiff-1" {
  source = "./modules/networking"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "uk-cardiff-1") ? 1 : 0
  providers = {
    oci = oci.uk-cardiff-1
  }
  compartment_id = module.compartment.id
  tags           = local.tags
}

module "functions_uk-cardiff-1" {
  source = "./modules/functions"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "uk-cardiff-1") ? 1 : 0
  providers = {
    oci = oci.uk-cardiff-1
  }
  tenancy_id        = var.tenancy_ocid
  compartment_id    = module.compartment.id
  subnet_id         = module.networking_uk-cardiff-1[0].subnet_id
  tags              = local.tags
  datadog_site      = var.datadog_site
  home_region       = local.home_region_name
  api_key_secret_id = length(module.kms) > 0 ? module.kms[0].api_key_secret_id : ""
  region_key        = local.subscribed_regions_map["uk-cardiff-1"].region_key
}

module "networking_uk-london-1" {
  source = "./modules/networking"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "uk-london-1") ? 1 : 0
  providers = {
    oci = oci.uk-london-1
  }
  compartment_id = module.compartment.id
  tags           = local.tags
}

module "functions_uk-london-1" {
  source = "./modules/functions"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "uk-london-1") ? 1 : 0
  providers = {
    oci = oci.uk-london-1
  }
  tenancy_id        = var.tenancy_ocid
  compartment_id    = module.compartment.id
  subnet_id         = module.networking_uk-london-1[0].subnet_id
  tags              = local.tags
  datadog_site      = var.datadog_site
  home_region       = local.home_region_name
  api_key_secret_id = length(module.kms) > 0 ? module.kms[0].api_key_secret_id : ""
  region_key        = local.subscribed_regions_map["uk-london-1"].region_key
}

module "networking_us-ashburn-1" {
  source = "./modules/networking"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "us-ashburn-1") ? 1 : 0
  providers = {
    oci = oci.us-ashburn-1
  }
  compartment_id = module.compartment.id
  tags           = local.tags
}

module "functions_us-ashburn-1" {
  source = "./modules/functions"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "us-ashburn-1") ? 1 : 0
  providers = {
    oci = oci.us-ashburn-1
  }
  tenancy_id        = var.tenancy_ocid
  compartment_id    = module.compartment.id
  subnet_id         = module.networking_us-ashburn-1[0].subnet_id
  tags              = local.tags
  datadog_site      = var.datadog_site
  home_region       = local.home_region_name
  api_key_secret_id = length(module.kms) > 0 ? module.kms[0].api_key_secret_id : ""
  region_key        = local.subscribed_regions_map["us-ashburn-1"].region_key
}

module "networking_us-chicago-1" {
  source = "./modules/networking"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "us-chicago-1") ? 1 : 0
  providers = {
    oci = oci.us-chicago-1
  }
  compartment_id = module.compartment.id
  tags           = local.tags
}

module "functions_us-chicago-1" {
  source = "./modules/functions"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "us-chicago-1") ? 1 : 0
  providers = {
    oci = oci.us-chicago-1
  }
  tenancy_id        = var.tenancy_ocid
  compartment_id    = module.compartment.id
  subnet_id         = module.networking_us-chicago-1[0].subnet_id
  tags              = local.tags
  datadog_site      = var.datadog_site
  home_region       = local.home_region_name
  api_key_secret_id = length(module.kms) > 0 ? module.kms[0].api_key_secret_id : ""
  region_key        = local.subscribed_regions_map["us-chicago-1"].region_key
}

module "networking_us-phoenix-1" {
  source = "./modules/networking"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "us-phoenix-1") ? 1 : 0
  providers = {
    oci = oci.us-phoenix-1
  }
  compartment_id = module.compartment.id
  tags           = local.tags
}

module "functions_us-phoenix-1" {
  source = "./modules/functions"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "us-phoenix-1") ? 1 : 0
  providers = {
    oci = oci.us-phoenix-1
  }
  tenancy_id        = var.tenancy_ocid
  compartment_id    = module.compartment.id
  subnet_id         = module.networking_us-phoenix-1[0].subnet_id
  tags              = local.tags
  datadog_site      = var.datadog_site
  home_region       = local.home_region_name
  api_key_secret_id = length(module.kms) > 0 ? module.kms[0].api_key_secret_id : ""
  region_key        = local.subscribed_regions_map["us-phoenix-1"].region_key
}

module "networking_us-sanjose-1" {
  source = "./modules/networking"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "us-sanjose-1") ? 1 : 0
  providers = {
    oci = oci.us-sanjose-1
  }
  compartment_id = module.compartment.id
  tags           = local.tags
}

module "functions_us-sanjose-1" {
  source = "./modules/functions"
  count  = local.is_current_region_home_region && contains(local.subscribed_regions_set, "us-sanjose-1") ? 1 : 0
  providers = {
    oci = oci.us-sanjose-1
  }
  tenancy_id        = var.tenancy_ocid
  compartment_id    = module.compartment.id
  subnet_id         = module.networking_us-sanjose-1[0].subnet_id
  tags              = local.tags
  datadog_site      = var.datadog_site
  home_region       = local.home_region_name
  api_key_secret_id = length(module.kms) > 0 ? module.kms[0].api_key_secret_id : ""
  region_key        = local.subscribed_regions_map["us-sanjose-1"].region_key
}

# End of autogenerated code
