# Title shown in Application Information tab.
title: Datadog Forwarding Infrastructure
# Sub Title shown in Application Information tab.
description: Setting up infrastructure for sending OCI metrics and logs to Datadog
schemaVersion: 1.1.0
version: 1.0
locale: en
variableGroups:
  - title: "Tenancy"
    variables:
      - ${tenancy_ocid}
      - ${region}
      - ${compartment_ocid}
      - ${current_user_ocid}
    visible: false
  - title: "Datadog Environment"
    variables:
      - ${datadog_app_key}
      - ${datadog_api_key}
      - ${datadog_site}
  - title: "(Optional) Choose Specific Subnet(s)"
    variables:
      - ${choose_subnet}
      - ${subnet_ocids}
  - title: "(Optional) Advanced Configuration"
    variables:
      - ${show_advanced_options}
      - ${compartment_id}
      - ${existing_group_id}
      - ${existing_user_id}

variables:
  choose_subnet:
    title: Choose Specific Subnet(s)
    type: boolean
    description: |
      Use an existing subnet for the Datadog QuickStart stack.
      
      (Recommended): If left blank, a new Virtual cloud network (VCN) and subnet will be created.
    required: false
    default: false

  show_advanced_options:
    title: Use advanced options
    type: boolean
    description: |
      Use an existing Compartment, Group, and User for the Datadog QuickStart stack.

      (Recommended): If left blank, a new Compartment, Group, and User will be created.
    required: false
    default: false

  # Networking Options
  subnet_ocids:
    title: Subnet OCIDs
    type: text
    multiline: true
    description: |
      Provide a list of OCID(s) for existing subnet(s) to use for the Datadog QuickStart stack. Enter one OCID per line. Do not add commas. 
      The Datadog QuickStart stack will be deployed in the region corresponding to each subnet. 
      Each subnet OCID should be in the format: ocid1.subnet.oc[0-9].* 
      Example: ocid1.subnet.oc1.iad.abcedfgh. 
      (Recommended): If left blank, a new Virtual cloud network (VCN) and subnet will be created in each region in this tenancy.
    required: false      
    default: ""
    visible: ${choose_subnet}

  # Datadog Environment
  datadog_api_key:
    title: Datadog API Key
    type: string
    description: |
      The API key for sending messages to Datadog endpoints. See <a href="https://docs.datadoghq.com/account_management/api-app-keys/" target="_blank">Datadog API Key</a> for more information.
    required: true
    sensitive: true
    password: true
    confirmation: true

  datadog_app_key:
    title: Datadog Application Key
    type: string
    description: |
      The Application key for creating and updating an integration with Datadog. See <a href="https://docs.datadoghq.com/account_management/api-app-keys/" target="_blank">Datadog Application Key</a> for more information.
    required: true
    sensitive: true
    password: true
    confirmation: true

  datadog_site:
    title: Datadog Site
    type: string
    description: |
      The site name for your Organization's Datadog endpoint (e.g. datadoghq.com, datadoghq.eu, etc.)
      This is the "Site Parameter" in the following <a href="https://docs.datadoghq.com/getting_started/site/#access-the-datadog-site" target="_blank">table from the Datadog documentation</a> .
    required: true

  compartment_id:
    title: Compartment
    description: |
      <strong>This is uncommon.</strong>
      Choose an existing compartment to place all the resources created by Datadog.
    type: oci:identity:compartment:id
    required: false
    default: null
    visible: ${show_advanced_options}

  existing_user_id:
    title: User ID
    type: string
    description: |
      <strong>This is uncommon.</strong>
      Provide the OCID of an existing OCI User for Datadog authentication. If you provide a Group, User ID cannot be left blank. The OCI User must belong to the current Identity Domain and be a member of the specified Group. 
      (Recommended): If both Group and User are left blank, a new Group and User will be created in the current Identity Domain.
    required: false
    default: null
    visible: ${show_advanced_options}

  existing_group_id:
    title: Group ID
    type: string
    description: |
      <strong>This is uncommon.</strong>
      Provide the OCID of an existing OCI Group for Datadog authentication. If you provide a Group, User ID cannot be left blank. The Group must belong to the current Identity Domain. 
      (Recommended): If both Group and User are left blank, a new Group and User will be created in the current Identity Domain.
    required: false
    default: null
    visible: ${show_advanced_options}