# Title shown in Application Information tab.
title: Datadog Metrics infra
# Sub Title shown in Application Information tab.
description: Setting up infra for sending OCI metrics to Datadog
schemaVersion: 1.1.0
version: 1.0
locale: en
variableGroups:
  - title: "Datadog Environment"
    variables:
      - ${datadog_api_key}
      - ${datadog_environment}
  - title: "Network options"
    variables:
      - ${create_vcn}
      - ${vcnCompartment}
      - ${existingVcn}
      - ${function_subnet_id}
  - title: "Metrics settings"
    variables:
      - ${metrics_namespaces}
      - ${metrics_compartments}
      - ${service_connector_target_batch_size_in_kbs}
  - title: "Function settings"
    variables:
      - ${function_app_shape}
      - ${oci_docker_username}
      - ${oci_docker_password}

variables:
  resource_name_prefix:
    type: string
    title: Resource prefix
    description: The prefix for the name of all of the resources.
    required: true
    default: datadog-metrics
  create_vcn:
    title: Create VCN
    description: Create virtual network (VCN) for the function setup. If using existing networking resources, de-select "Create VCN" and select the relevant VCN and subnet to use.
    type: boolean
    default: true

  compartment_ocid:
    # prepopulates available values for compartment
    required: true
    type: oci:identity:compartment:id
    description: The compartment OCID to where this terraform stack is created and the following networking resources, function, and connecter hub will be deployed.
    visible: false
  region:
    # prepopulates available values for compartment
    required: true
    type: string
    visible: false
  tenancy_ocid:
    required: true
    type: string
    visible: false        

# VCN
  vcnCompartment:
    # prepopulates available values for compartment
    type: oci:identity:compartment:id
    visible:
      not:
        - ${create_vcn}
  existingVcn:
    type: oci:core:vcn:id
    visible:
      not:
        - ${create_vcn}    
    dependsOn:
      compartmentId: ${vcnCompartment}
  function_subnet_id:
    title: Function Subnet OCID
    type: oci:core:subnet:id
    visible:
      not:
        - ${create_vcn}
    description: The subnet to be used by the function app that will be deployed. If "Create VCN" is selected, the new VCN will overwrite this selection..
    required: false
    dependsOn:
      compartmentId: ${vcnCompartment}
      vcnId: ${existingVcn}

# Datadog Environment
  datadog_api_key:
    title: Datadog API Key
    type: string
    description: The API key for sending message to datadog endpoints.
    required: true
    sensitive: true
    password: true
    confirmation: true
  datadog_environment:
    title: Datadog Environment Endpoint
    type: enum
    description: The endpoint to hit for sending the metrics. Varies by different datacenter.
    required: true
    enum:
      - ocimetrics-intake.datadoghq.com
      - ocimetrics-intake.us5.datadoghq.com
      - ocimetrics-intake.us3.datadoghq.com
      - ocimetrics-intake.datadoghq.eu
      - ocimetrics-intake.ap1.datadoghq.com
    allowMultiple: false

# Metrics namespace and connector hub
  metrics_compartments:
    title: Metrics compartments
    type: text
    required: true
    description: The list of metrics compartments. Enter comma separated list of OCID of compartments to monitor.
    default: ${tenancy_ocid}
    multiline: true

  metrics_namespaces:
    title: Metrics namespaces
    type: enum
    description: The list of namespaces to send metrics for, within their respective compartments. Remove any namespaces where metrics should not be sent.
    required: true
    additionalProps:
      allowMultiple: true
    default:
      - "oci_autonomous_database"
      - "oci_blockstore"
      - "oci_compute_infrastructure_health"
      - "oci_computeagent"
      - "oci_computecontainerinstance"
      - "oci_database"
      - "oci_database_cluster"
      - "oci_dynamic_routing_gateway"
      - "oci_faas"
      - "oci_fastconnect"
      - "oci_filestorage"
      - "oci_gpu_infrastructure_health"
      - "oci_lbaas"
      - "oci_mysql_database"
      - "oci_nat_gateway"
      - "oci_nlb"
      - "oci_objectstorage"
      - "oci_oke"
      - "oci_queue"
      - "oci_rdma_infrastructure_health"
      - "oci_service_connector_hub"
      - "oci_service_gateway"
      - "oci_vcn"
      - "oci_vpn"
      - "oci_waf"
      - "oracle_oci_database"   
    enum:
      - "oci_autonomous_database"
      - "oci_blockstore"
      - "oci_compute_infrastructure_health"
      - "oci_computeagent"
      - "oci_computecontainerinstance"
      - "oci_database"
      - "oci_database_cluster"
      - "oci_dynamic_routing_gateway"
      - "oci_faas"
      - "oci_fastconnect"
      - "oci_filestorage"
      - "oci_gpu_infrastructure_health"
      - "oci_lbaas"
      - "oci_mysql_database"
      - "oci_nat_gateway"
      - "oci_nlb"
      - "oci_objectstorage"
      - "oci_oke"
      - "oci_queue"
      - "oci_rdma_infrastructure_health"
      - "oci_service_connector_hub"
      - "oci_service_gateway"
      - "oci_vcn"
      - "oci_vpn"
      - "oci_waf"
      - "oracle_oci_database"
    

  # Function setup
  function_app_shape:
    title: Function Application shape
    type: enum
    description: The shape of the function application. The docker image should be built accordingly. Use GENERIC_ARM if using Oracle Resource manager stack.
    required: true
    enum:
      - GENERIC_ARM
      - GENERIC_X86
      - GENERIC_X86_ARM
    default: GENERIC_ARM
  oci_docker_username:
    title: OCI Docker registry user name
    type: string
    description: The user login for the OCI docker container registry to push function image. Not required if using an existing image path.
    required: true
    sensitive: true
  oci_docker_password:
    title: OCI Docker registry auth token
    type: password
    description: The user auth token for the OCI docker container registry. Used in creating function image.
    required: true
    sensitive: true
  service_connector_target_batch_size_in_kbs:
    title: Service Connector hub batch size
    type: nonNegativeInteger
    description: The batch size (in Kb) in which to send payload to target.
    required: false
    default: 5000
