# Title shown in Application Information tab.
title: Datadog Log Forwarding Infrastructure
# Sub Title shown in Application Information tab.
description: Setting up infrastructure for sending OCI Logs to Datadog
schemaVersion: 1.1.0
version: 1.0
locale: en
variableGroups:
  - title: "Tenancy"
    variables:
      - ${tenancy_ocid}
      - ${region}
      - ${compartment_ocid}
  - title: "Network options"
    variables:
      - ${create_vcn}
      - ${vcn_compartment}
      - ${existing_vcn}
      - ${subnet_ocid}
  - title: "Logging"
    variables:
      - ${exclude_services}
      - ${logging_compartments_csv}

variables:
  tenancy_ocid:
      visible: false

  region:
    visible: false

  compartment_ocid:
    visible: false
  
  resource_name_prefix:
    type: string
    title: Resource prefix
    description: The prefix for the name of all of the resources.
    required: true
    default: dd-logs


# VCN
  create_vcn:
    title: Create VCN
    description: Optional variable to create virtual network for the setup. Otherwise, choose an existing subnet from VCN
    type: boolean
    default: true
  
  vcn_compartment:
    # prepopulates available values for compartment
    type: oci:identity:compartment:id
    title: VCN Compartment
    description: The compartment to create the VCN in.
    required: true

  existing_vcn:
    type: oci:core:vcn:id
    title: Existing VCN
    description: The VCN to be used if not creating a new one.
    required: true
    visible:
      not:
        - ${create_vcn}
    dependsOn:
      compartmentId: ${vcn_compartment}

  subnet_ocid:
    title: Function Subnet OCID
    type: oci:core:subnet:id
    description: The OCID of the subnet to be used for the function app. Required if not creating the VCN.
    required: true
    visible:
      not:
        - ${create_vcn}
    dependsOn:
      compartmentId: ${vcn_compartment}
      vcnId: ${existing_vcn}

#Logging
  exclude_services:
    title: Exclude Services from Logging
    type: enum
    description: List of services to exclude from logging.
    required: false
    additionalProps:
      allowMultiple: true
    enum:
      - "oacnativeproduction"
      - "apigateway"
      - "adm"
      - "apm"
      - "cloud_guard_query_results_prod"
      - "cloud_guard_raw_logs_prod"
      - "och"
      - "oke-k8s-cp-prod"
      - "contentdeliverynetwork"
      - "dataflow"
      - "dataintegration"
      - "datascience"
      - "delegateaccessprod"
      - "devops"
      - "emaildelivery"
      - "cloudevents"
      - "filestorage"
      - "functions"
      - "goldengate"
      - "integration"
      - "loadbalancer"
      - "mediaflow"
      - "ocinetworkfirewall"
      - "objectstorage"
      - "operatoraccessprod"
      - "postgresql"
      - "oci_c3_vpn"
      - "flowlogs"
      - "waa"
      - "waf"

  logging_compartments_csv:
    title: Compartments CSV
    description: "Upload a CSV file containing the list of compartments. The file must include a column named 'compartment_id'."
    type: file
    required: true
