# Title shown in Application Information tab.
title: Datadog Log Forwarding Infrastructure
# Sub Title shown in Application Information tab.
description: Setting up infrastructure for sending OCI Logs to Datadog
schemaVersion: 1.1.0
version: 1.0
locale: en
variableGroups:
  - title: "Tenancy"
    variables:
      - ${tenancy_ocid}
      - ${region}
      - ${compartment_ocid}
      - ${current_user_ocid}
  - title: "Network options"
    variables:
      - ${create_vcn}
      - ${vcn_compartment}
      - ${existing_vcn}
      - ${subnet_ocid}
  - title: "Datadog Environment"
    variables:
      - ${datadog_endpoint}
      - ${datadog_api_key}
      - ${datadog_tags}
  - title: "Function settings"
    variables:
      - ${function_app_shape}
      - ${create_new_function_image}
      - ${function_image_path}
  - title: "Container Registry"
    variables:
      - ${use_different_service_user}
      - ${service_user_ocid}
      - ${create_auth_token}
      - ${auth_token_description}
      - ${auth_token}
    visible: ${create_new_function_image}
  - title: "Logging"
    variables:
      - ${exclude_services}
      - ${logging_compartments_csv}

variables:
  current_user_ocid:
    visible: false
  
  tenancy_ocid:
      visible: false

  region:
    visible: false

  compartment_ocid:
    visible: false
  
  resource_name_prefix:
    type: string
    title: Resource prefix
    description: The prefix for the name of all of the resources.
    required: true
    default: dd-logs


# VCN
  create_vcn:
    title: Create VCN
    description: Optional variable to create virtual network for the setup. Otherwise, choose an existing subnet from VCN
    type: boolean
    default: true
  
  vcn_compartment:
    # prepopulates available values for compartment
    type: oci:identity:compartment:id
    title: VCN Compartment
    description: The compartment to create the VCN in.
    required: true

  existing_vcn:
    type: oci:core:vcn:id
    title: Existing VCN
    description: The VCN to be used if not creating a new one.
    required: true
    visible:
      not:
        - ${create_vcn}
    dependsOn:
      compartmentId: ${vcn_compartment}

  subnet_ocid:
    title: Function Subnet OCID
    type: oci:core:subnet:id
    description: The OCID of the subnet to be used for the function app. Required if not creating the VCN.
    required: true
    visible:
      not:
        - ${create_vcn}
    dependsOn:
      compartmentId: ${vcn_compartment}
      vcnId: ${existing_vcn}

# Datadog Environment
  datadog_endpoint:
    title: Datadog Endpoint
    type: enum
    description: The endpoint to hit for sending the logs.
    required: true
    enum:
      - http-intake.logs.datadoghq.com
    allowMultiple: false

  datadog_api_key:
    title: Datadog API Key
    type: string
    description: The API key for sending message to datadog endpoints.
    required: true
    sensitive: true
    password: true
    confirmation: true

# Function setup
  function_app_shape:
    title: Function Application shape
    type: enum
    description: The shape of the function application. The docker image should be built accordingly. Use GENERIC_ARM if using Oracle Resource manager stack.
    required: true
    enum:
      - GENERIC_ARM
      - GENERIC_X86
      - GENERIC_X86_ARM
    default: GENERIC_ARM
  
  create_new_function_image:
    title: Create New Function Image
    description: Variable to create new function image. Otherwise, choose an existing image.
    required: true
    type: boolean
    default: true

  function_image_path:
    title: Function Image Path
    type: string
    required: true
    description: The full path of the function image. The image should be present in the container registry for the region and be compatible with the function application shape.
    visible:
      not:
        - ${create_new_function_image}

# Container Registry
  use_different_service_user:
    title: Use Different Service User
    description: Option to use a different service user for Docker login and pushing images.
    type: boolean
    required: true
    default: false

  service_user_ocid:
    title: Service User OCID
    type: string
    description: The OCID of the service user to be used for Docker login and pushing images.
    required: true
    default: ""
    visible: ${use_different_service_user}

  create_auth_token:
    title: Create Auth Token
    description: Variable to create auth token for the user. Otherwise, choose an existing auth token. If there are already 2 tokens, you need to delete one to create a new one.
    type: boolean
    required: true
    default: false
    visible: 
      not:
        - ${use_different_service_user}
  
  auth_token_description:
    title: Auth Token Description
    default: datadog-auth-token
    required: true
    visible: ${create_auth_token}
  
  auth_token:
    title: Auth Token
    type: password
    description: The auth token to be used for the container registry.
    sensitive: true
    required: true
    visible:
      not:
        - ${create_auth_token}

#Logging
  exclude_services:
    title: Exclude Services from Logging
    type: enum
    description: List of services to exclude from logging.
    required: false
    default: []
    additionalProps:
      allowMultiple: true
    enum:
      - "oacnativeproduction"
      - "apigateway"
      - "adm"
      - "apm"
      - "cloud_guard_query_results_prod"
      - "cloud_guard_raw_logs_prod"
      - "och"
      - "oke-k8s-cp-prod"
      - "contentdeliverynetwork"
      - "dataflow"
      - "dataintegration"
      - "datascience"
      - "delegateaccessprod"
      - "devops"
      - "emaildelivery"
      - "cloudevents"
      - "filestorage"
      - "functions"
      - "goldengate"
      - "integration"
      - "loadbalancer"
      - "mediaflow"
      - "ocinetworkfirewall"
      - "objectstorage"
      - "operatoraccessprod"
      - "postgresql"
      - "oci_c3_vpn"
      - "flowlogs"
      - "waa"
      - "waf"

  logging_compartments_csv:
    title: Compartments CSV
    description: "Upload a CSV file containing the list of compartments. The file must include a column named 'compartment_id'."
    type: file
    required: true
