# Policy for: .github/workflows/release.yml in DataDog/oracle-cloud-integration
issuer: https://token.actions.githubusercontent.com
subject: repo:DataDog/oracle-cloud-integration:ref:refs/heads/master

claim_pattern:
  event_name: workflow_dispatch
  job_workflow_ref: DataDog/oracle-cloud-integration/\.github/workflows/release\.yml@refs/heads/master
  ref: refs/heads/master
  repository: DataDog/oracle-cloud-integration

permissions:
  contents: write
