schema_version: 20180708
name: logs-forwarder
version: 0.0.1
runtime: go
build_image: fnproject/go:1.23-dev
run_image: fnproject/go:1.23
entrypoint: ./func
memory: 256
triggers:
- name: logs-forwarder
  type: http
  source: /logs-forwarder
